/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sharegogo_video_lib_LibInterface */

#ifndef _Included_com_sharegogo_video_lib_LibInterface
#define _Included_com_sharegogo_video_lib_LibInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sharegogo_video_lib_LibInterface
 * Method:    init
 * Signature: (Landroid/content/Context;)V
 */
JNIEXPORT void JNICALL Java_com_sharegogo_video_lib_LibInterface_init
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
